In [1]:
import numpy as np
import pandas as pd

In [2]:
p = 2
epsilon = .01

In [3]:
data = np.genfromtxt("Filtracion VR.csv", delimiter=",")
data = data[:10]
print(data)

[[ 0.013579  0.215377 -0.170891]
 [ 0.010493  0.226649 -0.173601]
 [ 0.020415  0.230665 -0.175927]
 [ 0.060064  0.241075 -0.140388]
 [ 0.057849  0.251924 -0.140969]
 [ 0.060421  0.253476 -0.126477]
 [ 0.062693  0.243492 -0.125203]
 [ 0.032816  0.221959 -0.172495]
 [ 0.026989  0.233526 -0.174706]
 [ 0.037539  0.239213 -0.169297]]


In [4]:
def distance(point1, point2, p):
    return np.power(np.sum(np.power(np.abs(point1 - point2), p)), 1/p)

$$
\left( \sum_{i=1}^{n} |x_{i} - x_{j}|^p \right)^{\frac{1}{p}}
$$


In [5]:
def calculate_distance_matrix(dataset, p):
    distance_matrix = np.zeros((dataset.shape[0], dataset.shape[0]))
    for i in range(dataset.shape[0]):
        for j in range(dataset.shape[0]):
            distance_matrix[i, j] = distance(dataset[i], dataset[j], p)
    return distance_matrix

In [6]:
distance_matrix = calculate_distance_matrix(data, p) 
print(distance_matrix)

[[0.         0.01199689 0.01748757 0.06125092 0.06473671 0.07495539
  0.0727326  0.02039504 0.02288599 0.03383456]
 [0.01199689 0.         0.01095375 0.06138808 0.06281929 0.07371
  0.0731498  0.02283716 0.0179062  0.03013079]
 [0.01748757 0.01095375 0.         0.0542534  0.05545549 0.0675731
  0.06726727 0.0155357  0.0072728  0.02025479]
 [0.06125092 0.06138808 0.0542534  0.         0.01108804 0.01863943
  0.01559929 0.04624645 0.04825628 0.03669568]
 [0.06473671 0.06281929 0.05545549 0.01108804 0.         0.01480007
  0.01852376 0.05018407 0.049285   0.03710177]
 [0.07495539 0.07371    0.0675731  0.01863943 0.01480007 0.
  0.0103182  0.06223354 0.06198175 0.05060209]
 [0.0727326  0.0731498  0.06726727 0.01559929 0.01852376 0.0103182
  0.         0.05994029 0.0618437  0.05094423]
 [0.02039504 0.02283716 0.0155357  0.04624645 0.05018407 0.06223354
  0.05994029 0.         0.01313918 0.01817235]
 [0.02288599 0.0179062  0.0072728  0.04825628 0.049285   0.06198175
  0.0618437  0.01313918 0

In [ ]:
def vietoris_rips_filtration(distance_matrix, epsilon):
    n = distance_matrix.shape[0]
    complex = []

    def add_simplex(simplex, max_distance):
        complex.append(simplex)
        if len(simplex) < n: # Si el simplejo aún no tiene tamaño n
            for i in range(max(simplex) + 1, n): # Para cada punto i que aún no está en el simplejo
                # Calcula la distancia máxima desde el primer punto en el simplejo hasta el punto i
                new_distance = max(max_distance, distance_matrix[simplex[0], i])  
                if new_distance <= epsilon: # Si esta distancia máxima es menor o igual a epsilon
                    # Agrega el punto i al simplejo y llama recursivamente a add_simplex
                    add_simplex(simplex + [i], new_distance) 

    for i in range(n): # Para cada punto i
        add_simplex([i], 0) # Inicia un nuevo simplejo con solo el punto i

    return complex

In [8]:
complex = vietoris_rips_filtration(distance_matrix, epsilon)
print(f"Epsilon {epsilon}: {complex}")

Epsilon 0.01: [[0], [1], [2], [2, 8], [3], [4], [5], [6], [7], [8], [9]]
